Fixed String Display in roles.php
publishpress/PublishPress-Capabilities pull request #1248
Opened 2024-12-19 13:55 UTC by DAnn2012

Fixed String Display in roles.php

2024-12-19 13:56 UTC, stevejburge commented
Thanks @DAnn2012

2025-01-09 05:59 UTC, olatechpro requested changes
Thanks for the changes @DAnn2012 but the string is just a placeholder and not needed to be displayed on that page although I see no reason for it to even be there at all.

Maybe you should simply update this pull request to remove it completely?

For example, if I merge your pull request right now, it'll result in this at the bottom of role table:
<img width="888" alt="Screenshot 2025-01-09 065654" src="https://github.com/user-attachments/assets/da122afd-1c3f-4232-89f8-9aa09843dbc8" />

2025-01-09 10:53 UTC, DAnn2012 commented
Hello @olatechpro 

but what is better, completely remove the "`<p>`" block:

https://github.com/publishpress/PublishPress-Capabilities/blob/994ee2e383b869a497ef34e20e40116d1757921a/includes/roles/roles.php#L33

or completely remove the "`<div>`" block:

https://github.com/publishpress/PublishPress-Capabilities/blob/994ee2e383b869a497ef34e20e40116d1757921a/includes/roles/roles.php#L32-L34

I look forward to your further suggestions.

Thanks.

2025-01-09 11:19 UTC, olatechpro commented
Hi @DAnn2012, removing the whole `<div class="form-wrap edit-term-notes">` seems to be the better suggestion as it doesn't have any usage in the codebase when I searched. It's meant for quick edit feature which we didn't use or have it code on the role screen.

2025-01-09 11:57 UTC, olatechpro approved these changes
Thanks

2025-01-09 11:57 UTC, merged